spring:
  application:
    name: kafka-consumer-dedup

server:
  port: 8085

ordersync:
  discovery-interval-millis: 5000

x-kafka-templates:
  producer-defaults: &producer-defaults
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
    value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  consumer-defaults: &consumer-defaults
    key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    trusted-packages: "com.example.kafkaconsumerdedup.*"

kafka:
  connections:
    order-sync:
      bootstrap-servers: localhost:9092

      producer:
        <<: *producer-defaults

      topics:
        navice-order-sync:
          name: naviceOrderSync
          partitions: 3
          replicas: 1
          consumers:
            audit-consumer:
              <<: *consumer-defaults
              group-id: naive-order-audit-group
              auto-offset-reset: earliest
              concurrency: 3

            monitor-consumer:
              <<: *consumer-defaults
              group-id: naive-order-monitor-group
              auto-offset-reset: latest
              concurrency: 1

        order-sync:
          name: orderSync
          partitions: 3
          replicas: 1
          consumers:
            execution-consumer:
              <<: *consumer-defaults
              group-id: order-execution-group
              auto-offset-reset: latest
              concurrency: 3

            reporting-consumer:
              <<: *consumer-defaults
              group-id: order-reporting-group
              auto-offset-reset: earliest
              concurrency: 3